# Generated by Django 5.2.12 on 2026-04-02 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memo',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos_to_check', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memo',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoworkflowlog',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='memos.memo'),
        ),
        migrations.AddField(
            model_name='memoworkflowlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='memo',
            index=models.Index(fields=['status', 'created_at'], name='memos_memo_status_f66c90_idx'),
        ),
        migrations.AddIndex(
            model_name='memoworkflowlog',
            index=models.Index(fields=['memo', 'action'], name='memos_memow_memo_id_f0062f_idx'),
        ),
    ]
